// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gs/gs.proto

package gs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ID int32

const (
	ID_ID_Enum ID = 0
	//测试
	ID_ID_G2C_GetInfos ID = 10000
	ID_ID_C2G_GetInfos ID = 10001
)

var ID_name = map[int32]string{
	0:     "ID_Enum",
	10000: "ID_G2C_GetInfos",
	10001: "ID_C2G_GetInfos",
}

var ID_value = map[string]int32{
	"ID_Enum":         0,
	"ID_G2C_GetInfos": 10000,
	"ID_C2G_GetInfos": 10001,
}

func (x ID) String() string {
	return proto.EnumName(ID_name, int32(x))
}

func (ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fb66f52ae6fe311d, []int{0}
}

//字符串map
type StrMap struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrMap) Reset()         { *m = StrMap{} }
func (m *StrMap) String() string { return proto.CompactTextString(m) }
func (*StrMap) ProtoMessage()    {}
func (*StrMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb66f52ae6fe311d, []int{0}
}

func (m *StrMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrMap.Unmarshal(m, b)
}
func (m *StrMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrMap.Marshal(b, m, deterministic)
}
func (m *StrMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrMap.Merge(m, src)
}
func (m *StrMap) XXX_Size() int {
	return xxx_messageInfo_StrMap.Size(m)
}
func (m *StrMap) XXX_DiscardUnknown() {
	xxx_messageInfo_StrMap.DiscardUnknown(m)
}

var xxx_messageInfo_StrMap proto.InternalMessageInfo

func (m *StrMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StrMap) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type G2S_GetInfos struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2S_GetInfos) Reset()         { *m = G2S_GetInfos{} }
func (m *G2S_GetInfos) String() string { return proto.CompactTextString(m) }
func (*G2S_GetInfos) ProtoMessage()    {}
func (*G2S_GetInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb66f52ae6fe311d, []int{1}
}

func (m *G2S_GetInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2S_GetInfos.Unmarshal(m, b)
}
func (m *G2S_GetInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2S_GetInfos.Marshal(b, m, deterministic)
}
func (m *G2S_GetInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2S_GetInfos.Merge(m, src)
}
func (m *G2S_GetInfos) XXX_Size() int {
	return xxx_messageInfo_G2S_GetInfos.Size(m)
}
func (m *G2S_GetInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_G2S_GetInfos.DiscardUnknown(m)
}

var xxx_messageInfo_G2S_GetInfos proto.InternalMessageInfo

func (m *G2S_GetInfos) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type S2G_GetInfos struct {
	Ret                  uint32    `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Values               []*StrMap `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *S2G_GetInfos) Reset()         { *m = S2G_GetInfos{} }
func (m *S2G_GetInfos) String() string { return proto.CompactTextString(m) }
func (*S2G_GetInfos) ProtoMessage()    {}
func (*S2G_GetInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb66f52ae6fe311d, []int{2}
}

func (m *S2G_GetInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2G_GetInfos.Unmarshal(m, b)
}
func (m *S2G_GetInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2G_GetInfos.Marshal(b, m, deterministic)
}
func (m *S2G_GetInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2G_GetInfos.Merge(m, src)
}
func (m *S2G_GetInfos) XXX_Size() int {
	return xxx_messageInfo_S2G_GetInfos.Size(m)
}
func (m *S2G_GetInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_S2G_GetInfos.DiscardUnknown(m)
}

var xxx_messageInfo_S2G_GetInfos proto.InternalMessageInfo

func (m *S2G_GetInfos) GetRet() uint32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *S2G_GetInfos) GetValues() []*StrMap {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("gs.ID", ID_name, ID_value)
	proto.RegisterType((*StrMap)(nil), "gs.StrMap")
	proto.RegisterType((*G2S_GetInfos)(nil), "gs.G2S_GetInfos")
	proto.RegisterType((*S2G_GetInfos)(nil), "gs.S2G_GetInfos")
}

func init() { proto.RegisterFile("proto/gs/gs.proto", fileDescriptor_fb66f52ae6fe311d) }

var fileDescriptor_fb66f52ae6fe311d = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2f, 0xd6, 0x4f, 0x2f, 0xd6, 0x03, 0xb3, 0x85, 0x98, 0xd2, 0x8b, 0x95, 0x0c,
	0xb8, 0xd8, 0x82, 0x4b, 0x8a, 0x7c, 0x13, 0x0b, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2,
	0x54, 0x09, 0x26, 0xb0, 0x18, 0x84, 0xa3, 0xa4, 0xc0, 0xc5, 0xe3, 0x6e, 0x14, 0x1c, 0xef, 0x9e,
	0x5a, 0xe2, 0x99, 0x97, 0x96, 0x5f, 0x8c, 0xac, 0x8f, 0x05, 0xac, 0x4f, 0xc9, 0x85, 0x8b, 0x27,
	0xd8, 0xc8, 0x1d, 0x45, 0x45, 0x51, 0x6a, 0x09, 0x58, 0x05, 0x6f, 0x10, 0x88, 0x29, 0xa4, 0xc4,
	0xc5, 0x06, 0x36, 0xac, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x4b, 0x2f, 0xbd, 0x58,
	0x0f, 0xe2, 0x8e, 0x20, 0xa8, 0x8c, 0x96, 0x2d, 0x17, 0x93, 0xa7, 0x8b, 0x10, 0x37, 0x17, 0xbb,
	0xa7, 0x4b, 0xbc, 0x6b, 0x5e, 0x69, 0xae, 0x00, 0x83, 0x90, 0x08, 0x17, 0xbf, 0xa7, 0x4b, 0xbc,
	0xbb, 0x91, 0x33, 0xdc, 0x6c, 0x81, 0x09, 0x7e, 0x50, 0x51, 0x67, 0x24, 0x1b, 0x05, 0x26, 0xfa,
	0x25, 0xb1, 0x81, 0xfd, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x38, 0x0f, 0xc4, 0x1f, 0xf8,
	0x00, 0x00, 0x00,
}
